export interface CountryPhone {
  code: string
  name: string
  flag: string
  dial: string
}

/* Complete list — all UN member states + commonly used territories (~240 entries) */
export const countries: CountryPhone[] = [
  // ── Africa ──────────────────────────────────────────────
  { code: 'DZ', name: 'Algérie', flag: '🇩🇿', dial: '+213' },
  { code: 'AO', name: 'Angola', flag: '🇦🇴', dial: '+244' },
  { code: 'BJ', name: 'Bénin', flag: '🇧🇯', dial: '+229' },
  { code: 'BW', name: 'Botswana', flag: '🇧🇼', dial: '+267' },
  { code: 'BF', name: 'Burkina Faso', flag: '🇧🇫', dial: '+226' },
  { code: 'BI', name: 'Burundi', flag: '🇧🇮', dial: '+257' },
  { code: 'CV', name: 'Cap-Vert', flag: '🇨🇻', dial: '+238' },
  { code: 'CM', name: 'Cameroun', flag: '🇨🇲', dial: '+237' },
  { code: 'CF', name: 'Rép. Centrafricaine', flag: '🇨🇫', dial: '+236' },
  { code: 'TD', name: 'Tchad', flag: '🇹🇩', dial: '+235' },
  { code: 'KM', name: 'Comores', flag: '🇰🇲', dial: '+269' },
  { code: 'CG', name: 'Congo', flag: '🇨🇬', dial: '+242' },
  { code: 'CD', name: 'RD Congo', flag: '🇨🇩', dial: '+243' },
  { code: 'CI', name: "Côte d'Ivoire", flag: '🇨🇮', dial: '+225' },
  { code: 'DJ', name: 'Djibouti', flag: '🇩🇯', dial: '+253' },
  { code: 'EG', name: 'Égypte', flag: '🇪🇬', dial: '+20' },
  { code: 'GQ', name: 'Guinée Équatoriale', flag: '🇬🇶', dial: '+240' },
  { code: 'ER', name: 'Érythrée', flag: '🇪🇷', dial: '+291' },
  { code: 'SZ', name: 'Eswatini', flag: '🇸🇿', dial: '+268' },
  { code: 'ET', name: 'Éthiopie', flag: '🇪🇹', dial: '+251' },
  { code: 'GA', name: 'Gabon', flag: '🇬🇦', dial: '+241' },
  { code: 'GM', name: 'Gambie', flag: '🇬🇲', dial: '+220' },
  { code: 'GE', name: 'Géorgie', flag: '🇬🇪', dial: '+995' },
  { code: 'GH', name: 'Ghana', flag: '🇬🇭', dial: '+233' },
  { code: 'GN', name: 'Guinée', flag: '🇬🇳', dial: '+224' },
  { code: 'GW', name: 'Guinée-Bissau', flag: '🇬🇼', dial: '+245' },
  { code: 'KE', name: 'Kenya', flag: '🇰🇪', dial: '+254' },
  { code: 'LS', name: 'Lesotho', flag: '🇱🇸', dial: '+266' },
  { code: 'LR', name: 'Liberia', flag: '🇱🇷', dial: '+231' },
  { code: 'LY', name: 'Libye', flag: '🇱🇾', dial: '+218' },
  { code: 'MG', name: 'Madagascar', flag: '🇲🇬', dial: '+261' },
  { code: 'MW', name: 'Malawi', flag: '🇲🇼', dial: '+265' },
  { code: 'ML', name: 'Mali', flag: '🇲🇱', dial: '+223' },
  { code: 'MR', name: 'Mauritanie', flag: '🇲🇷', dial: '+222' },
  { code: 'MU', name: 'Maurice', flag: '🇲🇺', dial: '+230' },
  { code: 'YT', name: 'Mayotte', flag: '🇾🇹', dial: '+262' },
  { code: 'MA', name: 'Maroc', flag: '🇲🇦', dial: '+212' },
  { code: 'MZ', name: 'Mozambique', flag: '🇲🇿', dial: '+258' },
  { code: 'NA', name: 'Namibie', flag: '🇳🇦', dial: '+264' },
  { code: 'NE', name: 'Niger', flag: '🇳🇪', dial: '+227' },
  { code: 'NG', name: 'Nigeria', flag: '🇳🇬', dial: '+234' },
  { code: 'RW', name: 'Rwanda', flag: '🇷🇼', dial: '+250' },
  { code: 'RE', name: 'La Réunion', flag: '🇷🇪', dial: '+262' },
  { code: 'SN', name: 'Sénégal', flag: '🇸🇳', dial: '+221' },
  { code: 'SC', name: 'Seychelles', flag: '🇸🇨', dial: '+248' },
  { code: 'SL', name: 'Sierra Leone', flag: '🇸🇱', dial: '+232' },
  { code: 'SO', name: 'Somalie', flag: '🇸🇴', dial: '+252' },
  { code: 'ZA', name: 'Afrique du Sud', flag: '🇿🇦', dial: '+27' },
  { code: 'SS', name: 'Soudan du Sud', flag: '🇸🇸', dial: '+211' },
  { code: 'SD', name: 'Soudan', flag: '🇸🇩', dial: '+249' },
  { code: 'ST', name: 'Sao Tomé-et-Príncipe', flag: '🇸🇹', dial: '+239' },
  { code: 'TZ', name: 'Tanzanie', flag: '🇹🇿', dial: '+255' },
  { code: 'TG', name: 'Togo', flag: '🇹🇬', dial: '+228' },
  { code: 'TN', name: 'Tunisie', flag: '🇹🇳', dial: '+216' },
  { code: 'UG', name: 'Ouganda', flag: '🇺🇬', dial: '+256' },
  { code: 'ZM', name: 'Zambie', flag: '🇿🇲', dial: '+260' },
  { code: 'ZW', name: 'Zimbabwe', flag: '🇿🇼', dial: '+263' },

  // ── Europe ──────────────────────────────────────────────
  { code: 'AL', name: 'Albanie', flag: '🇦🇱', dial: '+355' },
  { code: 'AD', name: 'Andorre', flag: '🇦🇩', dial: '+376' },
  { code: 'AT', name: 'Autriche', flag: '🇦🇹', dial: '+43' },
  { code: 'BY', name: 'Biélorussie', flag: '🇧🇾', dial: '+375' },
  { code: 'BE', name: 'Belgique', flag: '🇧🇪', dial: '+32' },
  { code: 'BA', name: 'Bosnie-Herzégovine', flag: '🇧🇦', dial: '+387' },
  { code: 'BG', name: 'Bulgarie', flag: '🇧🇬', dial: '+359' },
  { code: 'HR', name: 'Croatie', flag: '🇭🇷', dial: '+385' },
  { code: 'CY', name: 'Chypre', flag: '🇨🇾', dial: '+357' },
  { code: 'DK', name: 'Danemark', flag: '🇩🇰', dial: '+45' },
  { code: 'EE', name: 'Estonie', flag: '🇪🇪', dial: '+372' },
  { code: 'FI', name: 'Finlande', flag: '🇫🇮', dial: '+358' },
  { code: 'FR', name: 'France', flag: '🇫🇷', dial: '+33' },
  { code: 'DE', name: 'Allemagne', flag: '🇩🇪', dial: '+49' },
  { code: 'GR', name: 'Grèce', flag: '🇬🇷', dial: '+30' },
  { code: 'HU', name: 'Hongrie', flag: '🇭🇺', dial: '+36' },
  { code: 'IS', name: 'Islande', flag: '🇮🇸', dial: '+354' },
  { code: 'IE', name: 'Irlande', flag: '🇮🇪', dial: '+353' },
  { code: 'IT', name: 'Italie', flag: '🇮🇹', dial: '+39' },
  { code: 'XK', name: 'Kosovo', flag: '🇽🇰', dial: '+383' },
  { code: 'LV', name: 'Lettonie', flag: '🇱🇻', dial: '+371' },
  { code: 'LI', name: 'Liechtenstein', flag: '🇱🇮', dial: '+423' },
  { code: 'LT', name: 'Lituanie', flag: '🇱🇹', dial: '+370' },
  { code: 'LU', name: 'Luxembourg', flag: '🇱🇺', dial: '+352' },
  { code: 'MT', name: 'Malte', flag: '🇲🇹', dial: '+356' },
  { code: 'MD', name: 'Moldavie', flag: '🇲🇩', dial: '+373' },
  { code: 'MC', name: 'Monaco', flag: '🇲🇨', dial: '+377' },
  { code: 'ME', name: 'Monténégro', flag: '🇲🇪', dial: '+382' },
  { code: 'NL', name: 'Pays-Bas', flag: '🇳🇱', dial: '+31' },
  { code: 'MK', name: 'Macédoine du Nord', flag: '🇲🇰', dial: '+389' },
  { code: 'NO', name: 'Norvège', flag: '🇳🇴', dial: '+47' },
  { code: 'PL', name: 'Pologne', flag: '🇵🇱', dial: '+48' },
  { code: 'PT', name: 'Portugal', flag: '🇵🇹', dial: '+351' },
  { code: 'RO', name: 'Roumanie', flag: '🇷🇴', dial: '+40' },
  { code: 'RU', name: 'Russie', flag: '🇷🇺', dial: '+7' },
  { code: 'SM', name: 'Saint-Marin', flag: '🇸🇲', dial: '+378' },
  { code: 'RS', name: 'Serbie', flag: '🇷🇸', dial: '+381' },
  { code: 'SK', name: 'Slovaquie', flag: '🇸🇰', dial: '+421' },
  { code: 'SI', name: 'Slovénie', flag: '🇸🇮', dial: '+386' },
  { code: 'ES', name: 'Espagne', flag: '🇪🇸', dial: '+34' },
  { code: 'SE', name: 'Suède', flag: '🇸🇪', dial: '+46' },
  { code: 'CH', name: 'Suisse', flag: '🇨🇭', dial: '+41' },
  { code: 'UA', name: 'Ukraine', flag: '🇺🇦', dial: '+380' },
  { code: 'GB', name: 'Royaume-Uni', flag: '🇬🇧', dial: '+44' },
  { code: 'VA', name: 'Vatican', flag: '🇻🇦', dial: '+379' },

  // ── Amériques ───────────────────────────────────────────
  { code: 'AG', name: 'Antigua-et-Barbuda', flag: '🇦🇬', dial: '+1-268' },
  { code: 'AR', name: 'Argentine', flag: '🇦🇷', dial: '+54' },
  { code: 'BS', name: 'Bahamas', flag: '🇧🇸', dial: '+1-242' },
  { code: 'BB', name: 'Barbade', flag: '🇧🇧', dial: '+1-246' },
  { code: 'BZ', name: 'Belize', flag: '🇧🇿', dial: '+501' },
  { code: 'BO', name: 'Bolivie', flag: '🇧🇴', dial: '+591' },
  { code: 'BR', name: 'Brésil', flag: '🇧🇷', dial: '+55' },
  { code: 'CA', name: 'Canada', flag: '🇨🇦', dial: '+1' },
  { code: 'CL', name: 'Chili', flag: '🇨🇱', dial: '+56' },
  { code: 'CO', name: 'Colombie', flag: '🇨🇴', dial: '+57' },
  { code: 'CR', name: 'Costa Rica', flag: '🇨🇷', dial: '+506' },
  { code: 'CU', name: 'Cuba', flag: '🇨🇺', dial: '+53' },
  { code: 'DO', name: 'Rép. Dominicaine', flag: '🇩🇴', dial: '+1-809' },
  { code: 'EC', name: 'Équateur', flag: '🇪🇨', dial: '+593' },
  { code: 'SV', name: 'El Salvador', flag: '🇸🇻', dial: '+503' },
  { code: 'US', name: 'États-Unis', flag: '🇺🇸', dial: '+1' },
  { code: 'GT', name: 'Guatemala', flag: '🇬🇹', dial: '+502' },
  { code: 'GY', name: 'Guyana', flag: '🇬🇾', dial: '+592' },
  { code: 'HT', name: 'Haïti', flag: '🇭🇹', dial: '+509' },
  { code: 'HN', name: 'Honduras', flag: '🇭🇳', dial: '+504' },
  { code: 'JM', name: 'Jamaïque', flag: '🇯🇲', dial: '+1-876' },
  { code: 'MX', name: 'Mexique', flag: '🇲🇽', dial: '+52' },
  { code: 'NI', name: 'Nicaragua', flag: '🇳🇮', dial: '+505' },
  { code: 'PA', name: 'Panama', flag: '🇵🇦', dial: '+507' },
  { code: 'PY', name: 'Paraguay', flag: '🇵🇾', dial: '+595' },
  { code: 'PE', name: 'Pérou', flag: '🇵🇪', dial: '+51' },
  { code: 'SR', name: 'Suriname', flag: '🇸🇷', dial: '+597' },
  { code: 'TT', name: 'Trinité-et-Tobago', flag: '🇹🇹', dial: '+1-868' },
  { code: 'UY', name: 'Uruguay', flag: '🇺🇾', dial: '+598' },
  { code: 'VE', name: 'Venezuela', flag: '🇻🇪', dial: '+58' },

  // ── Asie ────────────────────────────────────────────────
  { code: 'AF', name: 'Afghanistan', flag: '🇦🇫', dial: '+93' },
  { code: 'BD', name: 'Bangladesh', flag: '🇧🇩', dial: '+880' },
  { code: 'BT', name: 'Bhoutan', flag: '🇧🇹', dial: '+975' },
  { code: 'BN', name: 'Brunei', flag: '🇧🇳', dial: '+673' },
  { code: 'KH', name: 'Cambodge', flag: '🇰🇭', dial: '+855' },
  { code: 'CN', name: 'Chine', flag: '🇨🇳', dial: '+86' },
  { code: 'TW', name: 'Taïwan', flag: '🇹🇼', dial: '+886' },
  { code: 'HK', name: 'Hong Kong', flag: '🇭🇰', dial: '+852' },
  { code: 'IN', name: 'Inde', flag: '🇮🇳', dial: '+91' },
  { code: 'ID', name: 'Indonésie', flag: '🇮🇩', dial: '+62' },
  { code: 'JP', name: 'Japon', flag: '🇯🇵', dial: '+81' },
  { code: 'KZ', name: 'Kazakhstan', flag: '🇰🇿', dial: '+7' },
  { code: 'KG', name: 'Kirghizistan', flag: '🇰🇬', dial: '+996' },
  { code: 'LA', name: 'Laos', flag: '🇱🇦', dial: '+856' },
  { code: 'MY', name: 'Malaisie', flag: '🇲🇾', dial: '+60' },
  { code: 'MV', name: 'Maldives', flag: '🇲🇻', dial: '+960' },
  { code: 'MN', name: 'Mongolie', flag: '🇲🇳', dial: '+976' },
  { code: 'MM', name: 'Myanmar', flag: '🇲🇲', dial: '+95' },
  { code: 'NP', name: 'Népal', flag: '🇳🇵', dial: '+977' },
  { code: 'KP', name: 'Corée du Nord', flag: '🇰🇵', dial: '+850' },
  { code: 'KR', name: 'Corée du Sud', flag: '🇰🇷', dial: '+82' },
  { code: 'PK', name: 'Pakistan', flag: '🇵🇰', dial: '+92' },
  { code: 'PH', name: 'Philippines', flag: '🇵🇭', dial: '+63' },
  { code: 'SG', name: 'Singapour', flag: '🇸🇬', dial: '+65' },
  { code: 'LK', name: 'Sri Lanka', flag: '🇱🇰', dial: '+94' },
  { code: 'TJ', name: 'Tadjikistan', flag: '🇹🇯', dial: '+992' },
  { code: 'TH', name: 'Thaïlande', flag: '🇹🇭', dial: '+66' },
  { code: 'TL', name: 'Timor oriental', flag: '🇹🇱', dial: '+670' },
  { code: 'TR', name: 'Turquie', flag: '🇹🇷', dial: '+90' },
  { code: 'TM', name: 'Turkménistan', flag: '🇹🇲', dial: '+993' },
  { code: 'UZ', name: 'Ouzbékistan', flag: '🇺🇿', dial: '+998' },
  { code: 'VN', name: 'Viêt Nam', flag: '🇻🇳', dial: '+84' },

  // ── Moyen-Orient ────────────────────────────────────────
  { code: 'BH', name: 'Bahreïn', flag: '🇧🇭', dial: '+973' },
  { code: 'IR', name: 'Iran', flag: '🇮🇷', dial: '+98' },
  { code: 'IQ', name: 'Irak', flag: '🇮🇶', dial: '+964' },
  { code: 'IL', name: 'Israël', flag: '🇮🇱', dial: '+972' },
  { code: 'JO', name: 'Jordanie', flag: '🇯🇴', dial: '+962' },
  { code: 'KW', name: 'Koweït', flag: '🇰🇼', dial: '+965' },
  { code: 'LB', name: 'Liban', flag: '🇱🇧', dial: '+961' },
  { code: 'OM', name: 'Oman', flag: '🇴🇲', dial: '+968' },
  { code: 'PS', name: 'Palestine', flag: '🇵🇸', dial: '+970' },
  { code: 'QA', name: 'Qatar', flag: '🇶🇦', dial: '+974' },
  { code: 'SA', name: 'Arabie Saoudite', flag: '🇸🇦', dial: '+966' },
  { code: 'SY', name: 'Syrie', flag: '🇸🇾', dial: '+963' },
  { code: 'AE', name: 'Émirats Arabes Unis', flag: '🇦🇪', dial: '+971' },
  { code: 'YE', name: 'Yémen', flag: '🇾🇪', dial: '+967' },

  // ── Océanie ─────────────────────────────────────────────
  { code: 'AU', name: 'Australie', flag: '🇦🇺', dial: '+61' },
  { code: 'FJ', name: 'Fidji', flag: '🇫🇯', dial: '+679' },
  { code: 'KI', name: 'Kiribati', flag: '🇰🇮', dial: '+686' },
  { code: 'MH', name: 'Îles Marshall', flag: '🇲🇭', dial: '+692' },
  { code: 'FM', name: 'Micronésie', flag: '🇫🇲', dial: '+691' },
  { code: 'NR', name: 'Nauru', flag: '🇳🇷', dial: '+674' },
  { code: 'NZ', name: 'Nouvelle-Zélande', flag: '🇳🇿', dial: '+64' },
  { code: 'PW', name: 'Palaos', flag: '🇵🇼', dial: '+680' },
  { code: 'PG', name: 'Papouasie-Nouvelle-Guinée', flag: '🇵🇬', dial: '+675' },
  { code: 'WS', name: 'Samoa', flag: '🇼🇸', dial: '+685' },
  { code: 'SB', name: 'Îles Salomon', flag: '🇸🇧', dial: '+677' },
  { code: 'TO', name: 'Tonga', flag: '🇹🇴', dial: '+676' },
  { code: 'TV', name: 'Tuvalu', flag: '🇹🇻', dial: '+688' },
  { code: 'VU', name: 'Vanuatu', flag: '🇻🇺', dial: '+678' },
]

/** Find the best default country by dial code prefix */
export function findCountryByDial(phone: string): CountryPhone | undefined {
  const cleaned = phone.replace(/[\s\-()]/g, '')
  return countries.find((c) => cleaned.startsWith(c.dial))
}