import { NextRequest, NextResponse } from 'next/server'
import { db } from '@/lib/db'
import { createHmac } from 'crypto'
import { generateInvoiceForPayment, generateReceiptForPayment } from '@/lib/documents'

function signatureCheck(body: string, secret: string, signature: string): boolean {
  const hmac = createHmac('sha256', secret)
  hmac.update(body)
  return hmac.digest('hex') === signature
}

export const runtime = 'nodejs'

interface LemonSqueezyWebhookBody {
  meta: {
    event_name: string
    custom_data: {
      userId?: string
      planType?: string
      currency?: string
    }
  }
  data: {
    id: string
    type: string
    attributes: {
      status: string
      user_email: string
      user_name: string
      customer_id: number
      order_id?: number
      product_id: number
      variant_id: number
      // Payment details (for auto-invoicing)
      total?: number          // in cents
      subtotal?: number       // in cents
      tax?: number            // in cents
      currency?: string       // e.g. 'USD', 'EUR'
      first_order_item: {
        id: number
        variant_id: number
        price?: number        // unit price in cents
      }
      subscription_id?: number
      ends_at?: string | null
      renews_at?: string | null
      trial_ends_at?: string | null
      created_at: string
      updated_at: string
    }
  }
}

// Map checkout planType to DB plan value
const VALID_PLANS = ['starter', 'pro', 'career_plus', 'employer', 'annual', 'lifetime', 'api', 'enterprise']
function resolvePlan(planType?: string): string {
  if (planType && VALID_PLANS.includes(planType)) return planType
  return 'pro' // fallback
}

// Convert LS currency code + amount (cents) to invoice params
function parseAmount(attrs: LemonSqueezyWebhookBody['data']['attributes']): { amount: number; currency: string } {
  const rawTotal = attrs.total ?? attrs.first_order_item?.price ?? 0
  const amount = rawTotal / 100 // cents → dollars/euros
  const currency = (attrs.currency || 'EUR').toUpperCase()
  // Normalize: LS sends 'USD', 'EUR', 'GBP' — our docs use these directly
  return { amount, currency: ['EUR', 'USD', 'GBP'].includes(currency) ? currency : 'EUR' }
}

/**
 * Auto-generate invoice + receipt after a successful payment.
 * This closes the paperless loop: payment → invoice → bilan (taxes).
 */
async function autoGenerateDocuments(params: {
  userId: string
  userEmail: string
  userName: string
  planType: string
  amount: number
  currency: string
  paidAt: Date
}): Promise<void> {
  try {
    // Generate invoice (FAC-YYYY-NNNN)
    const invoice = await generateInvoiceForPayment({
      userEmail: params.userEmail,
      userName: params.userName,
      plan: params.planType,
      amount: params.amount,
      currency: params.currency,
      userId: params.userId,
      paidAt: params.paidAt,
    })
    console.log(`[webhook] Invoice ${invoice.number} generated for user ${params.userId} (${params.amount} ${params.currency})`)

    // Generate receipt (REC-YYYY-NNNN)
    const receipt = await generateReceiptForPayment({
      userEmail: params.userEmail,
      userName: params.userName,
      amount: params.amount,
      currency: params.currency,
      description: `Abonnement ${params.planType} — HireNova`,
      userId: params.userId,
      paidAt: params.paidAt,
    })
    console.log(`[webhook] Receipt ${receipt.number} generated for user ${params.userId}`)

    // Both documents are now linked to the user and will be included in future bilans
    // (bilans query all paid invoices by paidAt date)
  } catch (err) {
    console.error('[webhook] Auto-invoicing failed:', err instanceof Error ? err.message : err)
    // Don't throw — webhook should still return 200 to prevent retries
  }
}

async function handleOrderCreated(body: LemonSqueezyWebhookBody) {
  const userId = body.meta.custom_data?.userId
  const planType = body.meta.custom_data?.planType
  const customerId = body.data.attributes.customer_id?.toString()
  const variantId = body.data.attributes.variant_id?.toString()
  const attrs = body.data.attributes

  if (!userId) {
    console.error('order_created: missing userId in custom_data')
    return
  }

  const plan = resolvePlan(planType)

  await db.user.update({
    where: { id: userId },
    data: {
      plan,
      lsCustomerId: customerId || undefined,
      lsVariantId: variantId || undefined,
    },
  })

  // ===== Auto-generate invoice + receipt (paperless loop) =====
  const { amount, currency } = parseAmount(attrs)
  if (amount > 0) {
    const user = await db.user.findUnique({
      where: { id: userId },
      select: { email: true, name: true },
    })
    await autoGenerateDocuments({
      userId,
      userEmail: attrs.user_email || user?.email || '',
      userName: attrs.user_name || user?.name || 'Client',
      planType: plan,
      amount,
      currency,
      paidAt: new Date(attrs.created_at || Date.now()),
    })
  }
}

async function handleSubscriptionCreated(body: LemonSqueezyWebhookBody) {
  const userId = body.meta.custom_data?.userId
  const planType = body.meta.custom_data?.planType
  const customerId = body.data.attributes.customer_id?.toString()
  const subId = body.data.attributes.subscription_id?.toString()
  const variantId = body.data.attributes.first_order_item?.variant_id?.toString()
  const attrs = body.data.attributes

  if (!userId) {
    console.error('subscription_created: missing userId in custom_data')
    return
  }

  const plan = resolvePlan(planType)

  await db.user.update({
    where: { id: userId },
    data: {
      plan,
      lsCustomerId: customerId || undefined,
      lsVariantId: variantId || undefined,
      lsSubId: subId || undefined,
    },
  })

  // ===== Auto-generate invoice + receipt for first subscription payment =====
  const { amount, currency } = parseAmount(attrs)
  if (amount > 0) {
    const user = await db.user.findUnique({
      where: { id: userId },
      select: { email: true, name: true },
    })
    await autoGenerateDocuments({
      userId,
      userEmail: attrs.user_email || user?.email || '',
      userName: attrs.user_name || user?.name || 'Client',
      planType: plan,
      amount,
      currency,
      paidAt: new Date(attrs.created_at || Date.now()),
    })
  }
}

async function handleSubscriptionUpdated(body: LemonSqueezyWebhookBody) {
  const customerId = body.data.attributes.customer_id?.toString()
  const subId = body.data.attributes.subscription_id?.toString()
  const status = body.data.attributes.status
  const attrs = body.data.attributes

  if (!customerId) return

  // Find user by LemonSqueezy customer ID
  const user = await db.user.findFirst({
    where: { lsCustomerId: customerId },
  })

  if (!user) {
    console.error('subscription_updated: no user found for customer', customerId)
    return
  }

  // LemonSqueezy subscription statuses: active, paused, cancelled, expired, unpaid
  // Keep the user's existing plan if active, otherwise downgrade to free
  const plan = status === 'active' ? (user.plan !== 'free' ? user.plan : 'pro') : 'free'

  await db.user.update({
    where: { id: user.id },
    data: {
      plan,
      lsSubId: subId || undefined,
    },
  })

  // ===== Auto-generate invoice for renewal payment (if active and has amount) =====
  if (status === 'active') {
    const { amount, currency } = parseAmount(attrs)
    if (amount > 0) {
      await autoGenerateDocuments({
        userId: user.id,
        userEmail: attrs.user_email || user.email || '',
        userName: attrs.user_name || user.name || 'Client',
        planType: plan,
        amount,
        currency,
        paidAt: new Date(attrs.updated_at || Date.now()),
      })
    }
  }
}

async function handleSubscriptionCancelledOrExpired(body: LemonSqueezyWebhookBody) {
  const customerId = body.data.attributes.customer_id?.toString()

  if (!customerId) return

  const user = await db.user.findFirst({
    where: { lsCustomerId: customerId },
  })

  if (!user) {
    console.error(`${body.meta.event_name}: no user found for customer`, customerId)
    return
  }

  // Downgrade to free, but keep lifetime if they had it
  if (user.plan === 'lifetime') return

  await db.user.update({
    where: { id: user.id },
    data: { plan: 'free', lsSubId: null },
  })
}

export async function POST(request: NextRequest) {
  const body = await request.text()
  const signature = request.headers.get('x-signature')

  if (!signature) {
    console.error('Missing x-signature header')
    return NextResponse.json({ error: 'Missing signature' }, { status: 400 })
  }

  const secret = process.env.LEMONSQUEEZY_WEBHOOK_SECRET
  if (!secret) {
    console.error('LEMONSQUEEZY_WEBHOOK_SECRET is not configured')
    return NextResponse.json({ error: 'Webhook not configured' }, { status: 500 })
  }

  // Verify webhook signature
  const isValid = signatureCheck(body, secret, signature)
  if (!isValid) {
    console.error('Webhook signature verification failed')
    return NextResponse.json({ error: 'Invalid signature' }, { status: 400 })
  }

  let parsedBody: LemonSqueezyWebhookBody
  try {
    parsedBody = JSON.parse(body)
  } catch {
    console.error('Failed to parse webhook body')
    return NextResponse.json({ error: 'Invalid JSON' }, { status: 400 })
  }

  const eventName = parsedBody.meta.event_name

  try {
    switch (eventName) {
      case 'order_created':
        await handleOrderCreated(parsedBody)
        break

      case 'subscription_created':
        await handleSubscriptionCreated(parsedBody)
        break

      case 'subscription_updated':
        await handleSubscriptionUpdated(parsedBody)
        break

      case 'subscription_cancelled':
      case 'subscription_expired':
        await handleSubscriptionCancelledOrExpired(parsedBody)
        break

      default:
        console.log(`Unhandled webhook event: ${eventName}`)
    }
  } catch (error) {
    console.error(`Error processing webhook ${eventName}:`, error)
    // Still return 200 to prevent retries
  }

  return NextResponse.json({ received: true }, { status: 200 })
}
